server:
  port: 9000
spring:
  application:
    name: zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8900/eureka
  instance:
    ip-address: true
zuul:
  prefix: /api
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
      strip-prefix: false
  ignored-services:
    - consumer-service
hystrix:
  commadnd:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectionTimeOut: 500
  ReadTimeOut: 1000
