server:
  port: 8900

spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8900/eureka
    register-with-eureka: true
  server:
    eviction-interval-timer-in-ms: 30000